import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import "./styles/container-styles.css";
import "./styles/image-styles.css";
import "./styles/border-styles.css";
import "./styles/text-styles.css";
import "./styles/button-styles.css";
import "./styles/colour-styles.css";
import "./styles/button-styles.css";

const funnel = Funnel_Display({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medical Portfolio's",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${funnel.className}`}>{children}</body>
    </html>
  );
}
